training:
  iterations_from: 1
  iterations_to: 100
  epochs: 100
  batch_size: 256
  rmse_threshold: 0.01
  samples_per_model: 4096
  bitness_from: 6
  bitness_to: 42
  input_dim: 64
  seed: 239
  model_dir: /tmp/circus

model:
  name: deepset
  n_points: 1
  phi_hidden: 128
  phi_out: 64
  rho_hidden: 128
  dropout: 0.1

optimizer:
  name: adam
  lr: 0.001
