sampler:
  bitness: 16
  train_samples: 32768
  validation_samples: 32768
  seed: 239
  samples:
    - key: block_128
      method: block
      reps: 128
      label: block 128
    - key: mix_128
      method: mix
      reps: 128
      label: mix 128

model:
  name: deepset
  phi_hidden: 512
  phi_out: 256
  rho_hidden: 512
  dropout: 0.3
  predict_batch_size: 1024

optimiser:
  train_epochs: 500
  batch_size: 256
  optimizer:
    name: adam
    lr: 0.001
  scheduler:
    name: reduce_lr_on_plateau
    patience: 5
    factor: 0.5
